'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Starship
    Public Property ID As Integer
    Public Property PersonID As Integer
    Public Property Name As String
    Public Property Type As String
    Public Property WarpCapable As Nullable(Of Boolean)

    Public Overridable Property Person As Person

End Class
